package com.CatacombeDelReCaduto.game.Entity;

public class ItemTest {
    public static void main(String[] args){
        Inventory inventario = new Inventory();
        Food mela = new Food("mela nutriente", "mela", 1, 5);
        Armor helmet = new Armor("forte elmo", "elmo", 5, 10);
        Item lanterna = new Item("utile", "lanterna", 2);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        System.out.println(inventario);
        inventario.removeItem("elmo");
        System.out.println(inventario);
        inventario.removeItem("elmo");
        System.out.println(inventario);
        inventario.removeItem("mela");
        inventario.removeItem("lanterna");
        inventario.removeItem("mela");
        System.out.println(inventario);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(helmet);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(lanterna);
        inventario.addItem(mela);
        inventario.addItem(helmet);
        inventario.addItem(lanterna);
        inventario.addItem(helmet);
        inventario.addItem(lanterna);
        System.out.println(inventario);
    }
}
